In [1]:
import pandas as pd
from tabulate import tabulate
from functools import partial
def flatten(xss):
    return [x for xs in xss for x in xs]

In [2]:
df = pd.read_csv(r"C:\Users\anves\Downloads\Impact_of_Remote_Work_on_Mental_Health.csv")

df

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,Medium,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,Medium,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,Medium,Anxiety,No,No Change,4,Unsatisfied,5,None,Poor,North America
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,High,Depression,Yes,Increase,3,Unsatisfied,3,None,Poor,Europe
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,High,None,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,EMP4996,32,Male,Sales,Consulting,4,Onsite,24,2,5,High,Burnout,Yes,Decrease,4,Neutral,1,Weekly,Average,Asia
4996,EMP4997,39,Female,Sales,Healthcare,27,Onsite,48,15,1,Low,Depression,Yes,Decrease,1,Satisfied,1,None,Average,Africa
4997,EMP4998,42,Female,Sales,Healthcare,21,Hybrid,34,1,4,High,Burnout,No,Increase,3,Satisfied,1,Daily,Poor,Oceania
4998,EMP4999,27,Female,Sales,Healthcare,26,Remote,58,0,5,Low,None,Yes,Increase,3,Unsatisfied,4,Daily,Average,Asia
4999,EMP5000,29,Male,HR,IT,30,Onsite,20,15,1,Low,Depression,Yes,No Change,3,Unsatisfied,5,None,Poor,Asia

In [3]:
df.columns

Index(['Employee_ID', 'Age', 'Gender', 'Job_Role', 'Industry',
       'Years_of_Experience', 'Work_Location', 'Hours_Worked_Per_Week',
       'Number_of_Virtual_Meetings', 'Work_Life_Balance_Rating',
       'Stress_Level', 'Mental_Health_Condition',
       'Access_to_Mental_Health_Resources', 'Productivity_Change',
       'Social_Isolation_Rating', 'Satisfaction_with_Remote_Work',
       'Company_Support_for_Remote_Work', 'Physical_Activity', 'Sleep_Quality',
       'Region'],
      dtype='object')

In [4]:
df.isnull().sum()

Employee_ID                          0
Age                                  0
Gender                               0
Job_Role                             0
Industry                             0
Years_of_Experience                  0
Work_Location                        0
Hours_Worked_Per_Week                0
Number_of_Virtual_Meetings           0
Work_Life_Balance_Rating             0
Stress_Level                         0
Mental_Health_Condition              0
Access_to_Mental_Health_Resources    0
Productivity_Change                  0
Social_Isolation_Rating              0
Satisfaction_with_Remote_Work        0
Company_Support_for_Remote_Work      0
Physical_Activity                    0
Sleep_Quality                        0
Region                               0
dtype: int64

In [5]:
data=df.dropna(axis=1)

In [6]:
data.shape

(5000, 20)

In [7]:
data.dtypes

Employee_ID                          object
Age                                   int64
Gender                               object
Job_Role                             object
Industry                             object
Years_of_Experience                   int64
Work_Location                        object
Hours_Worked_Per_Week                 int64
Number_of_Virtual_Meetings            int64
Work_Life_Balance_Rating              int64
Stress_Level                         object
Mental_Health_Condition              object
Access_to_Mental_Health_Resources    object
Productivity_Change                  object
Social_Isolation_Rating               int64
Satisfaction_with_Remote_Work        object
Company_Support_for_Remote_Work       int64
Physical_Activity                    object
Sleep_Quality                        object
Region                               object
dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder


if "Employee_ID" in data.columns:
    data = data.drop(columns=["Employee_ID"])


# Encode all categorical columns into numeric codes
label_encoders = {}
for col in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

data

,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,32,2,2,3,13,0,47,7,2,2,2,0,0,1,2,1,2,1,2
1,40,0,0,4,3,2,52,4,1,2,0,0,1,3,1,2,2,1,1
2,59,2,6,1,22,0,46,11,5,2,0,0,2,4,2,5,1,2,3
3,27,1,6,2,20,1,32,8,4,0,2,1,1,3,2,3,1,2,2
4,49,1,5,0,32,1,35,12,2,0,3,1,0,3,2,3,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,32,1,5,0,4,1,24,2,5,0,1,1,0,4,0,1,2,0,1
4996,39,0,5,3,27,1,48,15,1,1,2,1,0,1,1,1,1,0,0
4997,42,0,5,3,21,0,34,1,4,0,1,0,1,3,1,1,0,2,4
4998,27,0,5,3,26,2,58,0,5,1,3,1,1,3,2,4,0,0,1
4999,29,1,2,4,30,1,20,15,1,1,2,1,2,3,2,5,1,2,1

In [9]:
from sklearn.preprocessing import MinMaxScaler
scalers = {}

for feature in data.columns:
    scaler = MinMaxScaler()  # or MinMaxScaler()
    data[feature] = scaler.fit_transform(data[[feature]])
    scalers[feature] = scaler

In [10]:
data

,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,0.263158,0.666667,0.333333,0.500000,0.352941,0.0,0.675,0.466667,0.25,1.0,0.666667,0.0,0.0,0.00,1.0,0.00,1.0,0.5,0.4
1,0.473684,0.000000,0.000000,0.666667,0.058824,1.0,0.800,0.266667,0.00,1.0,0.000000,0.0,0.5,0.50,0.5,0.25,1.0,0.5,0.2
2,0.973684,0.666667,1.000000,0.166667,0.617647,0.0,0.650,0.733333,1.00,1.0,0.000000,0.0,1.0,0.75,1.0,1.00,0.5,1.0,0.6
3,0.131579,0.333333,1.000000,0.333333,0.558824,0.5,0.300,0.533333,0.75,0.0,0.666667,1.0,0.5,0.50,1.0,0.50,0.5,1.0,0.4
4,0.710526,0.333333,0.833333,0.000000,0.911765,0.5,0.375,0.800000,0.25,0.0,1.000000,1.0,0.0,0.50,1.0,0.50,1.0,0.0,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.263158,0.333333,0.833333,0.000000,0.088235,0.5,0.100,0.133333,1.00,0.0,0.333333,1.0,0.0,0.75,0.0,0.00,1.0,0.0,0.2
4996,0.447368,0.000000,0.833333,0.500000,0.764706,0.5,0.700,1.000000,0.00,0.5,0.666667,1.0,0.0,0.00,0.5,0.00,0.5,0.0,0.0
4997,0.526316,0.000000,0.833333,0.500000,0.588235,0.0,0.350,0.066667,0.75,0.0,0.333333,0.0,0.5,0.50,0.5,0.00,0.0,1.0,0.8
4998,0.131579,0.000000,0.833333,0.500000,0.735294,1.0,0.950,0.000000,1.00,0.5,1.000000,1.0,0.5,0.50,1.0,0.75,0.0,0.0,0.2
4999,0.184211,0.333333,0.333333,0.666667,0.852941,0.5,0.000,1.000000,0.00,0.5,0.666667,1.0,1.0,0.50,1.0,1.00,0.5,1.0,0.2

In [11]:
data.dtypes

Age                                  float64
Gender                               float64
Job_Role                             float64
Industry                             float64
Years_of_Experience                  float64
Work_Location                        float64
Hours_Worked_Per_Week                float64
Number_of_Virtual_Meetings           float64
Work_Life_Balance_Rating             float64
Stress_Level                         float64
Mental_Health_Condition              float64
Access_to_Mental_Health_Resources    float64
Productivity_Change                  float64
Social_Isolation_Rating              float64
Satisfaction_with_Remote_Work        float64
Company_Support_for_Remote_Work      float64
Physical_Activity                    float64
Sleep_Quality                        float64
Region                               float64
dtype: object

In [12]:
print(data.columns)

Index(['Age', 'Gender', 'Job_Role', 'Industry', 'Years_of_Experience',
       'Work_Location', 'Hours_Worked_Per_Week', 'Number_of_Virtual_Meetings',
       'Work_Life_Balance_Rating', 'Stress_Level', 'Mental_Health_Condition',
       'Access_to_Mental_Health_Resources', 'Productivity_Change',
       'Social_Isolation_Rating', 'Satisfaction_with_Remote_Work',
       'Company_Support_for_Remote_Work', 'Physical_Activity', 'Sleep_Quality',
       'Region'],
      dtype='object')

In [13]:
data.columns = [col.upper() for col in data.columns]

# Display the first few rows
data.head()

,AGE,GENDER,JOB_ROLE,INDUSTRY,YEARS_OF_EXPERIENCE,WORK_LOCATION,HOURS_WORKED_PER_WEEK,NUMBER_OF_VIRTUAL_MEETINGS,WORK_LIFE_BALANCE_RATING,STRESS_LEVEL,MENTAL_HEALTH_CONDITION,ACCESS_TO_MENTAL_HEALTH_RESOURCES,PRODUCTIVITY_CHANGE,SOCIAL_ISOLATION_RATING,SATISFACTION_WITH_REMOTE_WORK,COMPANY_SUPPORT_FOR_REMOTE_WORK,PHYSICAL_ACTIVITY,SLEEP_QUALITY,REGION
0,0.263158,0.666667,0.333333,0.500000,0.352941,0.0,0.675,0.466667,0.25,1.0,0.666667,0.0,0.0,0.00,1.0,0.00,1.0,0.5,0.4
1,0.473684,0.000000,0.000000,0.666667,0.058824,1.0,0.800,0.266667,0.00,1.0,0.000000,0.0,0.5,0.50,0.5,0.25,1.0,0.5,0.2
2,0.973684,0.666667,1.000000,0.166667,0.617647,0.0,0.650,0.733333,1.00,1.0,0.000000,0.0,1.0,0.75,1.0,1.00,0.5,1.0,0.6
3,0.131579,0.333333,1.000000,0.333333,0.558824,0.5,0.300,0.533333,0.75,0.0,0.666667,1.0,0.5,0.50,1.0,0.50,0.5,1.0,0.4
4,0.710526,0.333333,0.833333,0.000000,0.911765,0.5,0.375,0.800000,0.25,0.0,1.000000,1.0,0.0,0.50,1.0,0.50,1.0,0.0,0.6

In [14]:
print(data.columns)

Index(['AGE', 'GENDER', 'JOB_ROLE', 'INDUSTRY', 'YEARS_OF_EXPERIENCE',
       'WORK_LOCATION', 'HOURS_WORKED_PER_WEEK', 'NUMBER_OF_VIRTUAL_MEETINGS',
       'WORK_LIFE_BALANCE_RATING', 'STRESS_LEVEL', 'MENTAL_HEALTH_CONDITION',
       'ACCESS_TO_MENTAL_HEALTH_RESOURCES', 'PRODUCTIVITY_CHANGE',
       'SOCIAL_ISOLATION_RATING', 'SATISFACTION_WITH_REMOTE_WORK',
       'COMPANY_SUPPORT_FOR_REMOTE_WORK', 'PHYSICAL_ACTIVITY', 'SLEEP_QUALITY',
       'REGION'],
      dtype='object')

In [16]:
X = data.drop(['MENTAL_HEALTH_CONDITION'], axis=1)

y = data['MENTAL_HEALTH_CONDITION']

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [18]:

X_train.shape, X_test.shape

((3500, 18), (1500, 18))

In [ ]:
#one hot encoding is better ? but that doesn't matter here

In [21]:
#Final results using sets of different features 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report


# Re-define the target
target = 'Mental_Health_Condition'

# Define feature sets based on previous message
apriori_features_cleaned = [
    'Access_to_Mental_Health_Resources', 'Gender', 'Sleep_Quality',
    'Age', 'Work_Location', 'Satisfaction_with_Remote_Work',
    'Stress_Level', 'Hours_Worked_Per_Week'
]

causal_features = [
    'Stress_Level', 'Sleep_Quality', 'Region', 'Job_Role',
    'Years_of_Experience', 'Number_of_Virtual_Meetings',
    'Satisfaction_with_Remote_Work', 'Hours_Worked_Per_Week',
    'Work_Life_Balance_Rating', 'Access_to_Mental_Health_Resources'
]

chi2_features = [
    'Job_Role', 'Number_of_Virtual_Meetings', 'Hours_Worked_Per_Week',
    'Years_of_Experience', 'Region', 'Company_Support_for_Remote_Work',
    'Gender', 'Sleep_Quality', 'Social_Isolation_Rating',
    'Access_to_Mental_Health_Resources'
]

# Safe extraction for classification metrics
def safe_classification_metrics(report, label):
    return {
        f'{label} - Precision': report.get(label, {}).get('precision', float('nan')),
        f'{label} - Recall': report.get(label, {}).get('recall', float('nan')),
        f'{label} - F1': report.get(label, {}).get('f1-score', float('nan')),
    }

# Optimized evaluation function
def evaluate_random_forest_safe_optimized(features_subset, label_encoders):
    df_subset = df[features_subset + [target]].dropna().copy()

    for col in df_subset.select_dtypes(include='object').columns:
        if col not in label_encoders:
            le = LabelEncoder()
            df_subset[col] = le.fit_transform(df_subset[col])
            label_encoders[col] = le
        else:
            df_subset[col] = label_encoders[col].transform(df_subset[col])

    X = df_subset[features_subset]
    y = df_subset[target]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    rf = RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42)
    rf.fit(X_train, y_train)
    preds = rf.predict(X_test)
    report = classification_report(y_test, preds, output_dict=True)

    results = {}
    for label in ['Anxiety', 'Burnout', 'Depression']:
        results.update(safe_classification_metrics(report, label))
    results['Overall Accuracy'] = report.get('accuracy', float('nan'))

    return results

# Rebuild label encoders dictionary
label_encoders = {}

# Evaluate all three feature sets
rf_results_apriori = evaluate_random_forest_safe_optimized(apriori_features_cleaned, label_encoders)
rf_results_causal = evaluate_random_forest_safe_optimized(causal_features, label_encoders)
rf_results_chi2 = evaluate_random_forest_safe_optimized(chi2_features, label_encoders)

# Final DataFrame
rf_df = pd.DataFrame([rf_results_apriori, rf_results_causal, rf_results_chi2],
                     index=['Random Forest - Apriori', 'Random Forest - Causal', 'Random Forest - Chi2'])

import ace_tools as tools; tools.display_dataframe_to_user(name="Random Forest Results (Optimized)", dataframe=rf_df)

                        XG-BOOST Apriori  XG-BOOST Causal  XG-BOOST Chi2  \
Anxiety - Precision                0.638            0.726          0.648
Anxiety - Recall                   0.487            0.561          0.432
Anxiety - F1                       0.552            0.635          0.519
Burnout - Precision                0.501            0.572          0.551
Burnout - Recall                   0.730            0.803          0.875
Burnout - F1                       0.594            0.671          0.673
Depression - Precision             0.649            0.715          0.691
Depression - Recall                0.500            0.572          0.486
Depression - F1                    0.565            0.638          0.572
Overall Accuracy                   0.573            0.745          0.685

                        Random Forest Apriori  Random Forest Causal  \
Anxiety - Precision                     0.589                 0.726
Anxiety - Recall                        0.394                 0.561
Anxiety - F1                            0.472                 0.635
Burnout - Precision                     0.499                 0.572
Burnout - Recall                        0.819                 0.803
Burnout - F1                            0.620                 0.671
Depression - Precision                  0.639                 0.715
Depression - Recall                     0.432                 0.572
Depression - F1                         0.516                 0.638
Overall Accuracy                        0.550                 0.745

                        Random Forest Chi2
Anxiety - Precision                  0.648
Anxiety - Recall                     0.432
Anxiety - F1                         0.519
Burnout - Precision                  0.551
Burnout - Recall                     0.875
Burnout - F1                         0.673
Depression - Precision               0.691
Depression - Recall                  0.486
Depression - F1                      0.572
Overall Accuracy                     0.685